#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 24 11:49:04 2018

@author: behrenslab
"""

channels_m481 = [3,7,1,6,2,10,16,13,9,8,15,14,4,5,12,11,30,26,32,27,31,23,17,20,24,25,18,19,29,28,21,22]

import OpenEphys as op
import os

files_folder = '/media/behrenslab/My Book/Ephys_Reversal_Learning/data/Ephys 3 Tasks Reversal Learning/m481/12_blocks'

files = os.listdir(files_folder)

for file in files:
    ephys_folder = os.path.join(files_folder, file)
    print(ephys_folder)
    if ephys_folder =='/media/behrenslab/My Book/Ephys_Reversal_Learning/data/Ephys 3 Tasks Reversal Learning/m481/12_blocks/m481_2018-07-02_15-24-36':
        continue
    elif ephys_folder == '/media/behrenslab/My Book/Ephys_Reversal_Learning/data/Ephys 3 Tasks Reversal Learning/m481/12_blocks/m481_2018-06-30_15-09-25':
        continue
    else:
        op.pack_2(ephys_folder, filename =ephys_folder +'/'+'m481'+'.dat', channels =channels_m481, chprefix ='CH', dref = 'ave')
    
#/media/behrenslab/My Book/Ephys_Reversal_Learning/data/Ephys 3 Tasks Reversal Learning/m486/12_blocks/m486_2018-07-09_17-29-22